# Generated by Django 3.0.8 on 2020-08-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationtext', models.CharField(max_length=1000)),
                ('notificationdate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=50)),
                ('unitprice', models.IntegerField()),
                ('mfgdate', models.CharField(max_length=20)),
                ('expdate', models.CharField(max_length=20)),
            ],
        ),
    ]
